.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, LICENSE, README.md
Close #41 
Close #42 
Close #43
=> documentation(project): update readme and add doc and template files

.github/ISSUE_TEMPLATE.md
- Documentation
fix bad-formed markdown checkboxes in issue-template
Close #48 
- 
=> fix(documentation): fix bad-formed markdown checkboxes in issue-template

.github/ISSUE_TEMPLATE.md
- Documentation
add a question about egeo-theme version used by the reporter
Close #50 
-
=> fix(documentation): add a a question about egeo-theme version used by the reporter

README.md
- Documentation fix
fix file structure styles
-
=> docs(readme): fix file structure styles

CHANGELOG.md, src/components/_index.scss, src/components/_table.scss
- New component theme
Add table component theme
- [] Have the sth classes documented in the website
=> style(st-table) Add table component theme

.gitignore, CHANGELOG.md, src/components/_breadcrumbs.scss, src/components/_index.scss
Extract customizable breadcrumbs stylesfrom egeo to egeo-theme
- New component.
Theme of breadcrumbs 
- Add other information you consider important
=> feat (Breadcrumbs): theme of Breadcrumbs

CHANGELOG.md, src/components/_form-label.scss, src/components/_index.scss, src/components/_switch.scss
- New component theme
Add switch and form label themes
- Add other information you consider important
=> feat(st-switch): Add switch theme

src/components/_dropdown-menu.scss, src/components/_search.scss
- Improvements
Add styles for autocomplete menu in search
=> feat(st-search): add autocomplete menu styles

Jenkinsfile
=> build(jenkinsfile): update foss value from string to boolean

pom.xml
=> build(pom.xml): update pom.xml

src/components/_index.scss, src/components/_tree.scss
- New component.
Add basic styles for tree component
=> feat(st-tree): Add basic styles for tree component

src/components/_alerts.scss, src/components/_index.scss
- New component
add styles for alerts
=> feat(st-alerts): add styles for alerts

package.json
=> build(package.lock): update versions

CHANGELOG.md, src/components/_header.scss
=> refactor(header): Adapt to new design and UX

CHANGELOG.md, src/components/_header.scss
This reverts commit 3ad0341512d83c51aee643290d587e8bdf6f00a3.
=> Revert "refactor(header): Adapt to new design and UX (#104)"

CHANGELOG.md, src/components/_input.scss, src/components/_textarea.scss, src/settings/_colors.scss, src/settings/_forms.scss, src/settings/_index.scss
- Refactor. 
Refactor input & textarea
=> refactor(st-input && st-textarea): st-input & st-textarea refactor

CHANGELOG.md, src/grid.scss, src/settings/_grid.scss, src/utils/_grid.scss
Close #CCT-84
- Refactor
- Egeo grid moved from ui-base to egeo-theme.
- Refactor egeo grid.
=> refactor(grid): update the grid

CHANGELOG.md, src/components/_breadcrumbs.scss
Close CCT-50
- Refactor
st-breadcrumb refactor.
=> refactor(st-breadcrumb): Redefine breadcrumbs

CHANGELOG.md, src/components/_header.scss
Adapt header to new design provided by UX/Design
=> refactor(header): Update header style

CHANGELOG.md, src/components/_switch.scss
CTT-99
- Bugfix, New component, etc.
Add a description of your changes here.
- Add other information you consider important
=> style(st-switch): Add new styles

CHANGELOG.md, src/components/_radio.scss
- Refactor
Add new style to radio button accoding to UX definitions
- Add other information you consider important
=> refactor(st-radio): Add new style

CHANGELOG.md, src/components/_button.scss
Closes #CCT-143
- Bugfix
Fix broken button style
=> fix(st-button): Fix broken button style
